import React, { useState } from "react";
import { Modal, Button, Input, Typography, Tabs } from "antd";
import { CopyOutlined, LayoutOutlined } from "@ant-design/icons";

const { Title, Paragraph } = Typography;

const AiTemplateModal = ({
    open,
    onCancel,
    generateAiPrompt,
    copyToClipboard,
    onImport
}) => {
    const [headerInput, setHeaderInput] = useState("");
    const [bodyInput, setBodyInput] = useState("");
    const [footerInput, setFooterInput] = useState("");

    const handleImportClick = () => {
        onImport({
            header: headerInput,
            body: bodyInput,
            footer: footerInput
        });
        setHeaderInput("");
        setBodyInput("");
        setFooterInput("");
    };

    return (
        <Modal
            title={<span><LayoutOutlined /> AI HTML Template Generator</span>}
            open={open}
            onCancel={onCancel}
            footer={null}
            width={700}
            destroyOnClose
        >
            <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
                {/* Step 1: Copy AI Prompt section */}
                <div style={{ padding: "12px 16px", background: "#f4f4f5", borderRadius: "8px", border: "1px solid #e4e4e7" }}>
                    <Title level={5} style={{ margin: "0 0 4px 0", fontSize: "14px" }}>1. Copy AI Prompt</Title>
                    <Paragraph style={{ fontSize: "12px", margin: "0 0 12px 0", color: "#71717a" }}>
                        Copy this pre-configured prompt and paste it into ChatGPT, Claude, or any AI assistant. It includes your theme colors, fonts, and the list of available placeholders.
                    </Paragraph>
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                        <div style={{ display: "flex", gap: "12px" }}>
                            <Button
                                type="link"
                                onClick={() => {
                                    const prompt = generateAiPrompt();
                                    copyToClipboard(prompt, "Prompt copied! Paste it into ChatGPT (Ctrl+V) if not pre-filled.");
                                    window.open(`https://chatgpt.com/?q=${encodeURIComponent(prompt)}`, "_blank", "noopener,noreferrer");
                                }}
                            >
                                Open ChatGPT
                            </Button>
                            <Button
                                type="link"
                                onClick={() => {
                                    const prompt = generateAiPrompt();
                                    copyToClipboard(prompt, "Prompt copied! Paste it into Claude (Ctrl+V) if not pre-filled.");
                                    window.open(`https://claude.ai/new?q=${encodeURIComponent(prompt)}`, "_blank", "noopener,noreferrer");
                                }}
                            >
                                Open Claude
                            </Button>
                        </div>
                        <Button
                            type="primary"
                            icon={<CopyOutlined />}
                            onClick={() => copyToClipboard(generateAiPrompt(), "AI Prompt copied to clipboard!")}
                            size="small"
                        >
                            Copy Prompt
                        </Button>
                    </div>
                </div>

                {/* Step 2: Paste HTML Sections */}
                <div>
                    <Title level={5} style={{ margin: "0 0 4px 0", fontSize: "14px" }}>2. Paste HTML Sections</Title>
                    <Paragraph style={{ fontSize: "12px", margin: "0 0 12px 0", color: "#71717a" }}>
                        Paste the Header, Body, and Footer HTML sections generated by the AI into the respective tabs below.
                    </Paragraph>
                    <Tabs
                        defaultActiveKey="body"
                        type="card"
                        items={[
                            {
                                key: "header",
                                label: "Header HTML",
                                children: (
                                    <Input.TextArea
                                        placeholder="Paste Header HTML here..."
                                        rows={8}
                                        value={headerInput}
                                        onChange={(e) => setHeaderInput(e.target.value)}
                                        style={{ fontFamily: "monospace", fontSize: "12px" }}
                                    />
                                )
                            },
                            {
                                key: "body",
                                label: "Body HTML",
                                children: (
                                    <Input.TextArea
                                        placeholder="Paste Body HTML here..."
                                        rows={8}
                                        value={bodyInput}
                                        onChange={(e) => setBodyInput(e.target.value)}
                                        style={{ fontFamily: "monospace", fontSize: "12px" }}
                                    />
                                )
                            },
                            {
                                key: "footer",
                                label: "Footer HTML",
                                children: (
                                    <Input.TextArea
                                        placeholder="Paste Footer HTML here..."
                                        rows={8}
                                        value={footerInput}
                                        onChange={(e) => setFooterInput(e.target.value)}
                                        style={{ fontFamily: "monospace", fontSize: "12px" }}
                                    />
                                )
                            }
                        ]}
                        style={{ marginBottom: "15px" }}
                    />
                    <div style={{ display: "flex", justifyContent: "flex-end", gap: "10px" }}>
                        <Button onClick={onCancel}>Cancel</Button>
                        <Button
                            type="primary"
                            onClick={handleImportClick}
                            disabled={!headerInput.trim() && !bodyInput.trim() && !footerInput.trim()}
                        >
                            Import Sections
                        </Button>
                    </div>
                </div>
            </div>
        </Modal>
    );
};

export default AiTemplateModal;
